services:
  - type: web
    name: youtube-dublaj-backend
    env: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GOOGLE_TRANSLATE_API_KEY
        sync: false
      - key: GOOGLE_TTS_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
  - type: static
    name: youtube-dublaj-frontend
    rootDir: frontend
    staticPublishPath: .
    plan: free
